services:
  db:
    image: postgres:16
    container_name: m-motors-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: m_motors
      POSTGRES_USER: m_motors_user
      POSTGRES_PASSWORD: m_motors_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
